import { Inter, Roboto, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/compoents/Navbar/Navbar";
import Footer from "@/compoents/footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ThemeProvider>
        <div className={"container"}>
            <Navbar />
            {children}
            <Footer />
        </div>
          </ThemeProvider>
      </body>
    </html>
  );
}
